- .github/workflows/onpush.yml
- README.rst
- Add test coverage metric to codecov
- Add badges:
- lgtm.com alerts
- lgtm.com code quality
- GitHub Actions status
- codecov badge
> add test coverage publisher

- .github/workflows/onrelease.yml
- Add release pipeline to the project
- Fix names of the CI pipelines for more clarity
> add release pipeline

- README.rst
Fix badge syntax in the readme.
> fix badges syntax

- CHANGELOG.md
- README.rst
- docs/Makefile
- docs/index.html
- docs/source/cli.rst
- docs/source/quickstart.rst
This PR adds Github Pages compatible docs generator
> add github-compatible docs generation

- .github/dependabot.yml
this PR adds Github-compatible Dependabot config to keep track of the latest package versions.
> add github-compatible dependabot config

- tests/unit/test_deploy.py
Add mocks for DBFS service to make tests faster.
> Add mocks for dbfs service

- .github/workflows/codeql-analysis.yml
This PR adds CodeQL compatible checks to the repo.
> add CodeQL support

- dev-requirements.txt
Fix dev-requirements.txt to comply with versioning requirements in RTD.
> fix dev requirements file

- .github/workflows/codeql-analysis.yml
- dbx/commands/launch.py
- tests/unit/test_launch.py
> Add raw string parameters support

- CHANGELOG.md
- dbx/commands/deploy.py
- dbx/utils/policy_parser.py
- docs/source/index.rst
- docs/source/properties_propagation.rst
- setup.py
- tests/unit/test_policy_parser.py
- tests/unit/utils.py
> Implement cluster policy propagation

- README.rst
this is a docfix for image location. it also adds the code quality metric from lgtm.
> improve readme content

- Makefile
- dbx/commands/execute.py
- dbx/utils/common.py
This PR addresses issues in #48 an #49 . In particular, changes are the following:
1. execute command now tasks parameters section into account, file upload from local to remote is also supported
2. package file is now chosen based on file modification time, and this is generalized for both deploy and execute steps.
*Important* changes provided here shall be also reflected in the cicd-templates structure.
> Add parameter propagation and generalize local package finding process

- CHANGELOG.md
Describe the release changelog.
> Prepare release 0.1.4

- CONTRIBUTING.md
Mention the commit signature verification requirement.
> Explicitly require commit signature verification

- CHANGELOG.md
> fixing the changelog

- CHANGELOG.md
- dev-requirements.txt
- setup.py
- Removed the `pydash` as a package dependency as it is not used. 
- Unit tests still use it so, keeping it in the **dev-requirements.txt**
Minor change.
> Remove pydash from package dependencies as it is not used.

- CHANGELOG.md
- dbx/utils/common.py
- tests/unit/test_deploy.py
> Add explanation for IndexError exception during initialization of API client

- CHANGELOG.md
- dbx/commands/deploy.py
- dbx/utils/common.py
- docs/source/index.rst
- docs/source/multitask_jobs.rst
- docs/source/path_adjustment.rst
- prospector.yaml
- tests/deployment-configs/04-path-adjustment-policy.json
- tests/deployment-configs/04-path-adjustment-policy.yaml
- tests/unit/test_deploy.py
Proposed changes address #50 and re-use code from #51. It also provides a fix for #74
> Add strict path adjustment policy and FUSE path adjustment support

- CHANGELOG.md
> format changelog

- .coveragerc
- CHANGELOG.md
- dbx/commands/launch.py
- prospector.yaml
- setup.py
- tests/unit/test_adjust_path.py
- tests/unit/test_launch.py
This PR improves test coverage by multiple different additions to testing suite and addresses #68 . 
Also, it excludes vendor-based code from the codebase during codecov, since this code cannot be unittested.
> Improve coverage

- CHANGELOG.md
- dbx/utils/common.py
- setup.py
Fix the issue mentioned in #91 
> provide bugfix for #91

- CHANGELOG.md
- CONTRIBUTING.md
> [CHORE] update contrib

- CHANGELOG.md
- dbx/commands/deploy.py
- dbx/commands/execute.py
- dbx/utils/common.py
- docs/source/index.rst
- docs/source/named_properties.rst
- tests/deployment-configs/05-json-with-named-properties.json
- tests/deployment-configs/05-yaml-with-named-properties.yaml
- tests/unit/test_adjust_path.py
- tests/unit/test_execute.py
- tests/unit/test_named_properties.py
Add name-based properties as per #83 .
> add name-based parameters

- .github/workflows/onpush.yml
- CHANGELOG.md
- dbx/commands/datafactory.py
> fix the existing_cluster_id reference

- CHANGELOG.md
- dbx/commands/datafactory.py
> add jar task support

- docs/source/templates.rst
- tests/deployment-configs/01-yaml-test.json
- tests/deployment-configs/01-yaml-test.yaml
- tests/deployment-configs/02-yaml-with-vars-test.json
- tests/deployment-configs/02-yaml-with-vars-test.yaml
- tests/deployment-configs/03-multitask-job.json
- tests/deployment-configs/03-multitask-job.yaml
- tests/deployment-configs/04-json-with-env-vars.json
- tests/deployment-configs/04-yaml-with-env-vars.yaml
Address documentation issue in #111 
> fix library reference in docs

- CHANGELOG.md
- dbx/commands/deploy.py
This PR introduces a fix for task-based jobs, propagating the named properties resolution to the task level.
> add named properties resolution for tasks

- CHANGELOG.md
This PR finalizes 0.3.0 changes
> finalize the release changelog for 0.3.0

- .github/workflows/onrelease.yml
> fix token reference

- CHANGELOG.md
- dbx/commands/deploy.py
> [BUGFIX][#138] policy_name usage in multitask jobs

- CHANGELOG.md
- dbx/commands/deploy.py
- dbx/templates/projects/python_basic/components/.github/workflows/onpush.yml
- dbx/templates/projects/python_basic/components/.github/workflows/onrelease.yml
- dbx/templates/projects/python_basic/components/.gitlab-ci.yml
- dbx/templates/projects/python_basic/components/azure-pipelines.yml
- tests/unit/test_deploy.py
> [FEATURE][#141] add fallback to conf/deployment.yml

- dbx/commands/deploy.py
- dbx/commands/execute.py
- dbx/utils/common.py
- tests/unit/test_datafactory.py
- tests/unit/test_deploy.py
- tests/unit/test_launch.py
- tests/utils.py
Refactor code relevant to #141 
> [FEATURE][#141] refactor fallback to conf/deployment.yml

- docs/source/templates/python_basic.rst
Improve documentation for GH CI.
> [DOC] improve documentation for GitHub CI

- CHANGELOG.md
- dbx/commands/deploy.py
FInalize 0.3.1 release in the CHANGELOG
> [CHORE] finalize release 0.3.1

- contrib/CONTRIBUTING.md
> [CHORE] Fix email for contrib

- CHANGELOG.md
- dbx/utils/common.py
- tests/unit/test_file_uploader.py
This PR addresses issue in #156.
> [BUGFIX][#156] fix issue with non-dbfs based artifacts

- README.rst
- docs/source/permissions.rst
Just fixing a small typo in the Permissions documentation.
> fix: Typo in permissions docs

- .github/workflows/onpush.yml
- CHANGELOG.md
- dbx/utils/common.py
- setup.py
- tests/unit/test_file_uploader.py
Issues like #155 show that there might be some specifics with win-based platforms - let's add them into the testing pipeline.
> [CHORE] add windows testing suite

- CHANGELOG.md
- PULL_REQUEST_TEMPLATE.md
This PR finalizes the 0.3.3 release.
> [CHORE] Prepare 0.3.3 release

- CHANGELOG.md
- docs/source/multitask_jobs.rst
- setup.py
- tests/deployment-configs/06-yaml-jobs-api-2.1-example.yaml
[DOCFIX][#162] Provide documentation updates for Jobs API 2.1
> [DOCFIX][#162] Provide documentation updates for Jobs API 2.1

- CHANGELOG.md
Due to external reasons implementation of some features has been moved to the next release. 
Therefore the current codebase will be released right now to prevent the project from slugging on the new functionality.
> [CHORE] finalize 0.4.0 release

- docs/source/orchestration.rst
fix the path typo of the ADF example
- [ x] Documentation Update (if none of the other choices apply)
> [DOCFIX] typo in ADF file path

- CHANGELOG.md
- dbx/commands/datafactory.py
- dbx/commands/init.py
- dbx/utils/common.py
- dbx/utils/json.py
- tests/unit/test_datafactory.py
- tests/unit/test_deploy.py
- tests/unit/test_launch.py
- tests/unit/test_named_properties.py
This PR implements support for custom templates in dbx init.
> [FEATURE] add path and checkout options to dbx init

- dbx/templates/projects/python_basic/render/{{cookiecutter.project_name}}/README.md
> [DOCFIX] Provide command for JDK installation

- .readthedocs.yaml
RTD pipeline is unable to build the docs, this is a fix
> [DOCFIX] remove unused init files

- docs/source/examples/python_mtj.yml
> [DOCFIX] YAML formatting

- CHANGELOG.md
Prepare for the 0.5.0 release.
> [CHORE] Fix CHANGELOG

- CHANGELOG.md
- dbx/utils/dependency_manager.py
- tests/unit/test_dependency_manager.py
- tests/unit/test_deploy.py
fixes https://github.com/databrickslabs/dbx/issues/286
Use the requirements parser from `pkg_resources` to make library handling more robust.
> [BUGFIX] better parsing for requirements.txt

- CHANGELOG.md
> [CHORE] prepare 0.6.0 release

- .pre-commit-config.yaml
- Makefile
- setup.py
Add pre-commit hooks for development.
> [CHORE] add pre-commit hook

- .github/workflows/onrelease.yml
> [CHORE] increase Python version for release pipeline

- dbx/templates/projects/python_basic/render/{{cookiecutter.project_name}}/notebooks/sample_notebook.py
> [bugfix] provide correct package references in notebook

- CHANGELOG.md
- dbx/commands/execute.py
- dbx/templates/projects/python_basic/components/conf/deployment.yml
- tests/unit/test_execute.py
Addresses most of the multitask requests (#282,#84 ,#180 )
> [FEATURE] add execute support for multitask jobs

- CHANGELOG.md
- README.rst
- dbx/commands/execute.py
> [CHORE] prepare release 0.6.6

- tests/unit/sync/test_event_handler.py
This is a fix for the testing issue in #356.  The test `test_event_handler_create_file_force_includes` used `expected=1`, even though it actually expected 2.  After `get_events` is called, it asserts on there being 2 events.  This often works, because `get_events` returns all the events it got, and usually it gets both.  But if events are slow to be received, it could break early, due to the condition `expected=1` being met.  
To fix this, I've updated `get_events` to assert that the right number of events are received.  By doing this I can remove the asserts that followed `get_events`, and the potential for inconsistency that followed.   I also fixed `test_event_handler_create_file_force_includes` to expect the right number of events.
N/A
> Fix test_event_handler_create_file_force_includes

- CHANGELOG.md
- dbx/commands/deploy.py
- dbx/commands/execute.py
- dbx/utils/options.py
> [REFACTORING] move the deployment-file option

- CHANGELOG.md
- dbx/api/context.py
- dbx/api/execute.py
- dbx/commands/execute.py
- dbx/models/task.py
- tests/unit/commands/test_execute.py
- tests/unit/models/test_task.py
> [FEATURE] add wheel execute support

- dbx/templates/projects/python_basic/render/{{cookiecutter.project_name}}/README.md
- dbx/templates/projects/python_basic/render/{{cookiecutter.project_name}}/setup.py
- dbx/templates/projects/python_basic/render/{{cookiecutter.project_name}}/{{cookiecutter.project_slug}}/tasks/sample_etl_task.py
- dbx/templates/projects/python_basic/render/{{cookiecutter.project_name}}/{{cookiecutter.project_slug}}/tasks/sample_ml_task.py
- docs/source/templates/python_basic.rst
> [DOCS] improve python template docs

- dbx/callbacks.py
The callback is expected to return a value, otherwise all it's doing is (possibly) throwing an exception and clearing the value the user passes
> [BUGFIX] Fixing the jinja variables file callback

- .github/workflows/onpush.yml
- .github/workflows/onrelease.yml
- CHANGELOG.md
- dbx/commands/deploy.py
- dbx/commands/execute.py
- dbx/templates/projects/python_basic/components/.github/workflows/onpush.yml
- dbx/templates/projects/python_basic/components/.github/workflows/onrelease.yml
- dbx/templates/projects/python_basic/render/{{cookiecutter.project_name}}/{{cookiecutter.project_slug}}/common.py
- dbx/templates/projects/python_basic/render/{{cookiecutter.project_name}}/{{cookiecutter.project_slug}}/tasks/sample_etl_task.py
- dbx/utils/options.py
> [FEATURE] Jinja variables file support in execute

- CHANGELOG.md
- dbx/api/cluster.py
- dbx/api/config_reader.py
- dbx/api/configure.py
- dbx/api/storage/mlflow_based.py
- dbx/commands/configure.py
- dbx/commands/deploy.py
- dbx/commands/execute.py
- dbx/commands/launch.py
- dbx/constants.py
- dbx/models/deployment.py
- dbx/models/project.py
- dbx/models/task.py
- dbx/options.py
- dbx/utils/common.py
- dbx/utils/named_properties.py
- setup.py
- tests/deployment-configs/10-multitask-job-jobs.yaml
- tests/deployment-configs/10-multitask-job-workflows.yaml
- tests/unit/commands/test_configure.py
- tests/unit/commands/test_deploy.py
- tests/unit/commands/test_deploy_jinja_variables_file.py
- tests/unit/commands/test_execute.py
- tests/unit/commands/test_launch.py
- tests/unit/models/test_deployment.py
- tests/unit/utils/test_common.py
- tests/unit/utils/test_named_properties.py
- Since `dbx` is going to support DLT pipelines, `jobs` keyword becomes deprecated.
- Now the `jobs` is replaced with `workflows`, all old API interfaces will be marked as deprecated.
- Fixes #383
> [REFACTORING] introduce workflows 

- CHANGELOG.md
- dbx/commands/deploy.py
- dbx/commands/launch.py
- dbx/models/deployment.py
- tests/unit/commands/test_deploy.py
- tests/unit/models/test_deployment.py
> :technologist: [REFACTORING] add assets options

- CHANGELOG.md
- dbx/commands/sync/options.py
- dbx/commands/sync/sync.py
- tests/unit/sync/test_commands.py
> :sparkles: [FEATURE] add environment option for dbx sync

- CHANGELOG.md
- dbx/api/config_reader.py
- dbx/api/configure.py
- dbx/api/launch/functions.py
- dbx/commands/configure.py
- dbx/commands/sync/sync.py
- dbx/models/project.py
- dbx/templates/projects/python_basic/render/hooks/post_gen_project.py
- dbx/utils/common.py
- tests/unit/api/test_configure.py
- tests/unit/commands/test_configure.py
- tests/unit/commands/test_deploy.py
- tests/unit/commands/test_deploy_jinja_variables_file.py
> ✨[FEATURE] Add inplace jinja support

- Makefile
- setup.py
> :memo: Minor mkdocs fixes

- CHANGELOG.md
> :bookmark: bump to 0.7.1

- CHANGELOG.md
- docs/features/jinja_support.md
> :memo: Improve jinja docs

- CHANGELOG.md
- dbx/api/cluster.py
- dbx/api/execute.py
- dbx/api/launch/functions.py
- dbx/utils/__init__.py
> 🎨  add nice spinners for long-running processes

- CHANGELOG.md
- dbx/api/execute.py
- dbx/templates/projects/python_basic/components/.github/workflows/onpush.yml
- dbx/templates/projects/python_basic/components/.github/workflows/onrelease.yml
- dbx/templates/projects/python_basic/components/.gitlab-ci.yml
- dbx/templates/projects/python_basic/components/azure-pipelines.yml
- dbx/templates/projects/python_basic/components/conf/deployment.yml
- dbx/templates/projects/python_basic/render/{{cookiecutter.project_name}}/README.md
- dbx/templates/projects/python_basic/render/{{cookiecutter.project_name}}/setup.py
- dbx/templates/projects/python_basic/render/{{cookiecutter.project_name}}/tests/entrypoint.py
- dbx/templates/projects/python_basic/render/{{cookiecutter.project_name}}/tests/integration/e2e_test.py
- dbx/templates/projects/python_basic/render/{{cookiecutter.project_name}}/{{cookiecutter.project_slug}}/entrypoints.py
- docs/concepts/cluster_types.md
- docs/guides/python/python_quickstart.md
> 🧪add built-in capabilities for integration tests

- CHANGELOG.md
> :bookmark: Release 0.7.3

- CHANGELOG.md
- docs/concepts/testing.md
- docs/guides/python/integration_tests.md
- mkdocs.yml
> 📝 Add documentation about integration tests

- CHANGELOG.md
- docs/guides/python/devloop/mixed.md
> 📖 indents in quickstart doc

- CHANGELOG.md
- docs/guides/python/python_quickstart.md
> 📝 Improve quick start project structure docs

- .github/workflows/onpush.yml
- CHANGELOG.md
- mkdocs.yml
> :art: fix 404 by explicitly providing /en/latest

- CHANGELOG.md
- docs/features/build_management.md
- docs/guides/python/integration_tests.md
- docs/guides/python/python_quickstart.md
- docs/index.md
- docs/reference/deployment.md
- mkdocs.yml
Closes #462, #460, #459, #453. 
> :memo: Resolve some of the docs issues

- CHANGELOG.md
- dbx/templates/projects/python_basic/render/{{cookiecutter.project_name}}/README.md
- docs/concepts/cluster_types.md
- docs/guides/general/dependency_management.md
- docs/guides/python/python_quickstart.md
- mkdocs.yml
- setup.py
> 📝 Add dependency management documentation

- .github/workflows/onpush.yml
- CHANGELOG.md
- docs/guides/general/dependency_management.md
- docs/guides/jvm/jvm_devloop.md
- docs/guides/jvm/jvm_devops.md
> ✏️ Fix reference structures for `libraries` section

- CHANGELOG.md
- dbx/api/configure.py
- dbx/api/launch/processors.py
- dbx/api/launch/runners.py
- dbx/commands/configure.py
- dbx/models/job_clusters.py
- dbx/models/project.py
- dbx/templates/projects/python_basic/render/hooks/post_gen_project.py
- docs/concepts/cluster_types.md
- docs/features/assets.md
- tests/unit/api/launch/test_functions.py
- tests/unit/api/launch/test_processors.py
- tests/unit/api/launch/test_runners.py
- tests/unit/commands/test_configure.py
- tests/unit/models/test_job_clusters.py
> ✨ failsafe switch for assets-based shared job clusters

- CHANGELOG.md
- dbx/api/launch/runners.py
- dbx/utils/__init__.py
- tests/unit/api/launch/test_runners.py
> 🩹 Re-introduce the failsafe behaviour for assets-based property preprocessing

- CHANGELOG.md
> 🔖 Bump to 0.7.6

- CHANGELOG.md
- dbx/commands/sync/options.py
- docs/concepts/cluster_types.md
- docs/faq.md
> 📖 Add documentation on the differences between `dbx execute` and `dbx launch`

- CHANGELOG.md
- dbx/templates/projects/python_basic/render/{{cookiecutter.project_name}}/README.md
- docs/features/named_properties.md
- docs/features/permissions_management.md
- docs/reference/deployment.md
> 📖 fix broken link in the generated README.md in Python template

- dbx/commands/deploy.py
> 🩹 fix DLT pipeline order resolution

- CHANGELOG.md
- setup.py
> 🩹 Remove explicit wheel dependency

- CHANGELOG.md
- dbx/api/services/jobs.py
- tests/unit/api/test_jobs_service.py
- tests/unit/commands/test_launch.py
> ⚡️ Use improved method for job search

- CHANGELOG.md
- dbx/models/workflow/common/workflow.py
> 🩹 Make `pause_status` property optional

- CHANGELOG.md
- dbx/api/adjuster/adjuster.py
- tests/unit/api/adjuster/test_complex.py
> 🚨 Make traversal process fail-safe for dictionaries

- CHANGELOG.md
- dbx/api/execute.py
- dbx/models/validators.py
- dbx/models/workflow/common/parameters.py
- dbx/models/workflow/v2dot1/task.py
- dbx/options.py
- docs/guides/general/passing_parameters.md
- tests/unit/commands/test_execute.py
- tests/unit/models/test_parameters.py
- tests/unit/models/test_task.py
> 🩹 fix type recognition of `named_parameters` in `python_wheel_task`

- CHANGELOG.md
- docs/concepts/artifact_storage.md
- setup.py
> 🔨 Add support for extras for cloud file operations

- docs/faq.md
Added a new FAQ : Can I have multiple `deployment files` ?
> Updated faq.md

- CHANGELOG.md
- dbx/models/workflow/v2dot1/task.py
fix #660 , make `warehouse_id` optional in dbt task.
> fix/#660/make warehouse_id optinal in dbt task

- CHANGELOG.md
- docs/extras/styles.css
- docs/index.md
- mkdocs.yml
- setup.py
> 👔 Docs: added footer navigation,  deleted the version layover

- CHANGELOG.md
- README.md
> 👔 Docs: deleted lgtm badges from readme

- CHANGELOG.md
- docs/guides/general/dependency_management.md
> 🩹 Update default dbx version in the template

- CHANGELOG.md
- README.md
- dbx/api/launch/contexts.py
- dbx/api/launch/functions.py
- dbx/commands/launch.py
- docs/features/headers.md
- docs/guides/general/custom_templates.md
- mkdocs.yml
- tests/unit/commands/test_launch.py
> 🩹 Fix the bug with repetitive launch ops

- CHANGELOG.md
> 🔖 prepare 0.8.8 release

- CHANGELOG.md
- docs/faq.md
- docs/guides/general/passing_parameters.md
> 🔗 fix broken links in the docs

- CHANGELOG.md
> 📝 fix release string in changelog

- README.md
Added a pointer to DABs
- [ x] Documentation Update (if none of the other choices apply)
> Added pointer to DABs

- .github/workflows/release.yml
> Switch to using GitHub OIDC for PyPI

- README.md
- docs/extras/styles.css
- docs/overrides/main.html
> Introduce maintenance mode and add links to Python for DABs
